name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      run: xcodebuild clean build test -project PrayersTimes.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=Any iOS Simulator Device" ONLY_ACTIVE_ARCH=YES
